<?php

namespace Pepe\SistemBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EgresoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EgresoRepository extends EntityRepository
{
}
