<?php

namespace Pepe\SistemBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PagoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PagoRepository extends EntityRepository
{
}
